Object.defineProperties(String.prototype, {
	reset: {get: function(){ return '\x1b[0m' + this.replace('\x1b[0m', '');}},
	bold: {get: function(){ return '\x1b[1m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	dim: {get: function(){ return '\x1b[2m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	underscore: {get: function(){ return '\x1b[4m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	blink: {get: function(){ return '\x1b[5m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	reverse: {get: function(){ return '\x1b[7m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	hidden: {get: function(){ return '\x1b[8m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	black: {get: function(){ return '\x1b[30m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	red: {get: function(){ return '\x1b[31m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	green: {get: function(){ return '\x1b[32m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	yellow: {get: function(){ return '\x1b[33m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	blue: {get: function(){ return '\x1b[34m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	magenta: {get: function(){ return '\x1b[35m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	cyan: {get: function(){ return '\x1b[36m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	white: {get: function(){ return '\x1b[37m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_black: {get: function(){ return '\x1b[40m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_red: {get: function(){ return '\x1b[41m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_green: {get: function(){ return '\x1b[42m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_yellow: {get: function(){ return '\x1b[43m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_blue: {get: function(){ return '\x1b[44m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_magenta: {get: function(){ return '\x1b[45m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_cyan: {get: function(){ return '\x1b[46m' + this.replace('\x1b[0m', '') + '\x1b[0m';}},
	bg_white: {get: function(){ return '\x1b[47m' + this.replace('\x1b[0m', '') + '\x1b[0m';}}
});
